module.exports = {
    name: 'chocola',
    description: "Chocola self introduction!",
    execute(message, args){
        message.channel.send('https://youtu.be/MWDFRIL7LoQ')
        message.channel.send('Chocola (ショコラ Shokora) is a cheerful and straightforward catgirl with a dog-like personality who is very fond of her master. She is Vanilla’s twin sister and the youngest among the Minaduki catgirls. She’s not good at dealing with complicated stuff, but she is always friendly and energetic. She tends to leap into action before fully thinking things through. Despite her clumsy moments, her go-getter attitude earns plenty of love from everybody around her.')
        message.channel.send('**Appearance**')
        message.channel.send('Chocola has long brunette hair in two twintails with two small ribbons a top her head, matching her red and white dress, with stockings and pink shoes, brighter than the other colors she wears.')
        message.channel.send('She receives a silver colored Bell although it is not mentioned what corresponding rank or status comes with the color a catgirl obtains after taking her bell exam.')
        message.channel.send('**Personality**')
        message.channel.send('Chocola is a cheerful and energetic Catgirl as Kashou himself describes her, happy-go-lucky. She doesnt usually get upset, and even when she does, she often swings back to being as cheery as usual, though occasionally she can be genuinely sad about something. She is curious, and has a childlike outlook on things, which is fitting as she and Vanilla are mentioned to be only 9 months old in human terms.')
        message.channel.send('**Attributes**')
        message.channel.send('Race : Catgirl')
        message.channel.send('Breed : Mix Breed')
        message.channel.send('Gender : Female')
        message.channel.send('Age : 9 months')
        message.channel.send('**Characteristics**')
        message.channel.send('Complexion : Pale')
        message.channel.send('Height(Kid) : 125cm')
        message.channel.send('Height(Adult) : 152cm')
        message.channel.send('Weight(Kid) : 24.5kg')
        message.channel.send('3 Size(Kid) : 61cm,52cm,67cm')
        message.channel.send('3 Size(Adult) : 75cm,54cm,76cm')
        message.channel.send('Hair Colour : Brown')
        message.channel.send('Eye Colour : Amber')
        message.channel.send('Occupation : La Soleil employee')
        message.channel.send('**Relationships**')
        message.channel.send('Azuki - Older Sister')
        message.channel.send('Maple - Older Sister')
        message.channel.send('Cinnamon - Older Sister')
        message.channel.send('Coconut - Older Sister')
        message.channel.send('Vanilla - Biological Twin Sister')
        message.channel.send('Shigure - Owner')
        message.channel.send('Kashou - Owner and Partner')
        message.channel.send('**Background - Early Life**')
        message.channel.send('Chocola, together with her twin Vanilla, were found by Kashou and Shigure abandoned at the side of the road as young catgirls. The two Minaduki decided to adopt and bring them home. At first, she and Vanilla were scared due to the fact that they were surrounded by unfamiliar faces. They were unable to eat or speak to anyone and a few days later, reached a point that they does only drink some water. Due to the combination of malnutrition and cold weather, they both became cripplingly ill. They lay in bed, scared and in pain, unable to do anything but cry out. Despite their apprehensions, Kashou was by their side to reassure them. His kindness lead to Chocola developing affection for him. When morning finally arrived, Kashou brought them to the hospital and never left their company. The girls developed their trust towards others and made themselves more acquainted with the rest of the Minaduki household. They eventually recovered and since then, Chocola started loving her master Kashou.')
        message.channel.send('**Trivia**')
        message.channel.send('Chocola name is a pun on the word chocolate.')
        message.channel.send('Chocola typically expresses herself in third person.')
        message.channel.send('Chocola has trouble reading Kanji.')
        message.channel.send('Chocola can only count from 1 to 9.')
        message.channel.send('Chocola and Vanilla cat breeds were unknown until the release of the Nekopara OVA website, where they were confirmed to be mixed breeds.')
        message.channel.send('https://static.wikia.nocookie.net/nekopara/images/3/3c/Ch_cho_img_02.png/revision/latest/scale-to-width-down/310?cb=20150312042230');
    }
}